title: JiraMetrics
email: mbowler@gargoylesoftware.com
description: >- # this means to ignore newlines until "baseurl:"
  A tool for extracting useful data from Jira
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jirametrics.org" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: jekyll-theme-so-simple
plugins:
  # - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-image-size
  - jekyll-seo-tag

google_analytics: G-M5D87W2CHY

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"

paginate: 10  # amount of posts to show per page
paginate_path: /page:num/

feed:
  posts_limit: 10

search_full_content: true
# logo: '/assets/images/site_icon.png'
skin: "/assets/css/skins/light.css"

copyright: '&copy; 2022-2025 <a href="http://gargoylesoftware.com">Gargoyle Software Inc.</a>'
